name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release jar
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: 17
    - name: Mvn package
      run: mvn clean package 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          target/*.jar